on:
    push:
        tags:
            - v*
  
name: Latest Release

defaults:
    run:
        shell: bash

jobs:
    lint:
        name: Lint files
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-go@v5
          with:
              go-version: '1.20.5'

        - name: golangci-lint
          uses: golangci/golangci-lint-action@v6
          with:
              version: latest

    test:
        name: Run tests
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-go@v5
          with:
              go-version: '1.20.5'

        - run: go test -v -cover
